M48
; DRILL file {KiCad 7.0.9} date Mon Oct 14 21:48:47 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-14T21:48:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X66.0Y-54.0
X66.0Y-142.0
X160.9Y-142.0
X161.0Y-54.0
X220.5Y-54.0
X220.5Y-142.0
T0
M30
